//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quizsubmision
    {
        public int quizsubmissionid { get; set; }
        public Nullable<int> quizId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> completeAt { get; set; }
        public string quizresult { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
